[package]
name = "net"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
config = { path = "../config" }
const-str = "0.4.0"
upnp = { path = "../upnp" }
