[package]
name = "net"
version = "0.1.0"
edition = "2021"

[features]
default = ["upnp"]
upnp = ["dep:upnp"]

[dependencies]
async-std = "1.12.0"
config = { path = "../config" }
const-str = "0.4.0"
upnp = { path = "../upnp", optional = true }
